anchor = 'smart'
bgColor = 'ffffff'
resampleFilter = 'box'
[avif]
    compression = 'lossy'
    encoderSpeed = 10
    hint = 'photo'
    quality = 60
[exif]
    disableDate = false
    disableLatLong = false
    excludeFields = 'GPS|Exif|Exposure[M|P|B]|Contrast|Resolution|Sharp|JPEG|Metering|Sensing|Saturation|ColorSpace|Flash|WhiteBalance'
    includeFields = ''
[jpeg]
    quality = 75
[meta]
    fields = ['! *{GPS,Exif,Exposure[MPB],Contrast,Resolution,Sharp,JPEG,Metering,Sensing,Saturation,ColorSpace,Flash,WhiteBalance}*']
    sources = ['exif', 'iptc']
[webp]
    compression = 'lossy'
    hint = 'photo'
    method = 2
    quality = 75
    useSharpYuv = false