[en]
    contentDir = 'content'
    disabled = false
    locale = 'en-US'
    direction = 'ltr'
    label = 'English'
    title = "Matteo Pettenò's Portfolio"
    weight = 1
[it]
    contentDir = 'content'
    disabled = true
    locale = 'it-IT'
    direction = 'ltr'
    label = 'Italian'
    title = "Portfolio di Matteo Pettenò"
    weight = 2