[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "Matteo Pettenò's Portfolio"
    weight = 0
[it]
    contentDir = 'content/it'
    disabled = true
    languageCode = 'it-iT'
    languageDirection = 'ltr'
    languageName = 'Italian'
    title = "Portfolio di Matteo Pettenò"
    weight = 1
