[mediaTypes.'application/json']
delimiter = '.'
suffixes = ['json']
[mediaTypes.'application/manifest+json']
delimiter = '.'
suffixes = ['webmanifest']
[mediaTypes.'application/octet-stream']
delimiter = '.'
[mediaTypes.'application/pdf']
delimiter = '.'
suffixes = ['pdf']
[mediaTypes.'application/rss+xml']
delimiter = '.'
suffixes = ['xml', 'rss']
[mediaTypes.'application/source-map']
delimiter = '.'
suffixes = ['map']
[mediaTypes.'application/toml']
delimiter = '.'
suffixes = ['toml']
[mediaTypes.'application/wasm']
delimiter = '.'
suffixes = ['wasm']
[mediaTypes.'application/xml']
delimiter = '.'
suffixes = ['xml']
[mediaTypes.'application/yaml']
delimiter = '.'
suffixes = ['yaml', 'yml']
[mediaTypes.'font/otf']
delimiter = '.'
suffixes = ['otf']
[mediaTypes.'font/ttf']
delimiter = '.'
suffixes = ['ttf']
[mediaTypes.'font/woff']
delimiter = '.'
suffixes = ['woff']
[mediaTypes.'font/woff2']
delimiter = '.'
suffixes = ['woff2']
[mediaTypes.'image/avif']
delimiter = '.'
suffixes = ['avif']
[mediaTypes.'image/bmp']
delimiter = '.'
suffixes = ['bmp']
[mediaTypes.'image/gif']
delimiter = '.'
suffixes = ['gif']
[mediaTypes.'image/heic']
delimiter = '.'
suffixes = ['heic']
[mediaTypes.'image/heif']
delimiter = '.'
suffixes = ['heif']
[mediaTypes.'image/jpeg']
delimiter = '.'
suffixes = ['jpg', 'jpeg', 'jpe', 'jif', 'jfif']
[mediaTypes.'image/png']
delimiter = '.'
suffixes = ['png']
[mediaTypes.'image/svg+xml']
delimiter = '.'
suffixes = ['svg']
[mediaTypes.'image/tiff']
delimiter = '.'
suffixes = ['tif', 'tiff']
[mediaTypes.'image/webp']
delimiter = '.'
suffixes = ['webp']
[mediaTypes.'text/asciidoc']
delimiter = '.'
suffixes = ['adoc', 'asciidoc', 'ad']
[mediaTypes.'text/calendar']
delimiter = '.'
suffixes = ['ics']
[mediaTypes.'text/css']
delimiter = '.'
suffixes = ['css']
[mediaTypes.'text/csv']
delimiter = '.'
suffixes = ['csv']
[mediaTypes.'text/html']
delimiter = '.'
suffixes = ['html', 'htm']
[mediaTypes.'text/javascript']
delimiter = '.'
suffixes = ['js', 'jsm', 'mjs']
[mediaTypes.'text/jsx']
delimiter = '.'
suffixes = ['jsx']
[mediaTypes.'text/markdown']
delimiter = '.'
suffixes = ['md', 'mdown', 'markdown']
[mediaTypes.'text/org']
delimiter = '.'
suffixes = ['org']
[mediaTypes.'text/pandoc']
delimiter = '.'
suffixes = ['pandoc', 'pdc']
[mediaTypes.'text/plain']
delimiter = '.'
suffixes = ['txt']
[mediaTypes.'text/rst']
delimiter = '.'
suffixes = ['rst']
[mediaTypes.'text/tsx']
delimiter = '.'
suffixes = ['tsx']
[mediaTypes.'text/typescript']
delimiter = '.'
suffixes = ['ts']
[mediaTypes.'text/x-gotmpl']
delimiter = '.'
suffixes = ['gotmpl']
[mediaTypes.'text/x-sass']
delimiter = '.'
suffixes = ['sass']
[mediaTypes.'text/x-scss']
delimiter = '.'
suffixes = ['scss']
[mediaTypes.'video/3gpp']
delimiter = '.'
suffixes = ['3gpp', '3gp']
[mediaTypes.'video/mp4']
delimiter = '.'
suffixes = ['mp4']
[mediaTypes.'video/mpeg']
delimiter = '.'
suffixes = ['mpg', 'mpeg']
[mediaTypes.'video/ogg']
delimiter = '.'
suffixes = ['ogv']
[mediaTypes.'video/webm']
delimiter = '.'
suffixes = ['webm']
[mediaTypes.'video/x-msvideo']
delimiter = '.'
suffixes = ['avi']