[[main]]
    identifier = 'about'
    name = 'about'
    pageRef = '/about'
    parent = ''
    post = ''
    pre = ''
    title = 'about me'
    weight = 10
    [main.params]
[[main]]
    identifier = 'projects'
    name = 'projects'
    pageRef = '/projects'
    parent = ''
    post = ''
    pre = ''
    title = 'projects'
    weight = 20
    [main.params]
[[main]]
    identifier = 'research-activity'
    name = 'research'
    pageRef = '/projects/research'
    parent = 'projects'
    post = ''
    pre = ''
    title = 'research activity'
    weight = 10
    [main.params]
[[main]]
    identifier = 'professional-exp'
    name = 'work'
    pageRef = '/projects/work'
    parent = 'projects'
    post = ''
    pre = ''
    title = 'professional experience'
    weight = 20
    [main.params]
[[main]]
    identifier = 'creative-projects'
    name = 'creative'
    pageRef = '/projects/creative'
    parent = 'projects'
    post = ''
    pre = ''
    title = 'creative projects'
    weight = 30
    [main.params]
[[main]]
    identifier = 'computer-music-projects'
    name = 'computer music'
    pageRef = '/projects/computer-music'
    parent = 'projects'
    post = ''
    pre = ''
    title = 'computer music projects'
    weight = 40
    [main.params]
[[main]]
    identifier = 'sasp-projects'
    name = 'sound synthesis & processing'
    pageRef = '/projects/sasp'
    parent = 'projects'
    post = ''
    pre = ''
    title = 'sound analysis synthesis & processing'
    weight = 50
    [main.params]
[[main]]
    identifier = 'musical-acoutics-projects'
    name = 'musical acoustics'
    pageRef = '/projects/musical-acoustics'
    parent = 'projects'
    post = ''
    pre = ''
    title = 'musical acoustics'
    weight = 60
    [main.params]
[[main]]
    identifier = 'resume'
    name = 'resume'
    url = '/mpetteno-resume.pdf'
    parent = ''
    post = ''
    pre = ''
    title = 'resume'
    weight = 30
    [main.params]
        rel = 'external'
        target = '_blank'
[[main]]
    identifier = 'contactme'
    name = 'contact me'
    pageRef = '/contactme'
    parent = ''
    post = ''
    pre = ''
    title = 'contact me'
    weight = 40
    [main.params]
