[disqus]
    disable = false
[googleAnalytics]
    disable = true
    respectDoNotTrack = false
[instagram]
    disable = false
    simple = false
[twitter]
    disable = false
    enableDNT = false
    simple = false
[vimeo]
    disable = false
    enableDNT = false
    simple = false
[youTube]
    disable = false
    privacyEnhanced = false